package com.z4hyoung.lifecyclesamples;

import androidx.lifecycle.LifecycleObserver;

/**
 * No EmptyObserver_LifecycleAdapter will be generated by annotationProcessor because there is no methods annotated
 * with {@link androidx.lifecycle.OnLifecycleEvent}
 */
final class EmptyObserver implements LifecycleObserver {
}
